### ISSUE TITLE
[PARTY] child process exited with code 1…

### ISSUE THREAD

**Issue by pedrosouza9966** [ibratabian17/OpenParty#2]
i hosted openparty to glitch.com for testing, but it seems that’s not working and im always getting this child log. i’ve tried edit `package.json` to start `node server.js` but now my website get the error `{"error":404,"message":"Path Not Recognized"}`, is that normal? also, if i run server.js locally, and edit isPublic to false, would i need to patch the exe or something to make it work? any reply would be useful :)
![2D018EC0-02A1-4B7A-8CCA-3294EC82B83B](https://github.com/ibratabian17/openparty/assets/157870982/38cca63a-c7c7-40f3-a328-696d1d44995f)

**Comment by ibratabian17** [comment]
1. Can you give me the proper logs? (All) it seems like the nodejs glitch can't run this application properly
2. website getting error {"error":404,"message":"Path Not Recognized"} is normal, because it is an invalid request
3. isPublic is useful for VPS users, for example If isPublic off, then those outside the server/computer (including the local network) cannot access it
4. use pm2 cuz we broke run.js

**Comment by pedrosouza9966** [comment]
![9F15B195-4E9A-40E2-9247-C15255431045](https://github.com/user-attachments/assets/af9427ec-0ebf-49e8-808e-c38a9bc4d1e0)
It’s working fine now, i’m using pm2 ;)
